# Generated by Django 5.2.7 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_stations_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='location',
        ),
        migrations.AddField(
            model_name='stations',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stations',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stations',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
