# Generated by Django 5.2.7 on 2025-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_stations_location_stations_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='lga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='state_code',
            field=models.CharField(blank=True, db_column='statecode', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
