# Generated by Django 5.2.7 on 2025-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_stations_address_stations_lga_stations_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stations',
            name='lga',
            field=models.CharField(blank=True, db_column='lga', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stations',
            name='name',
            field=models.CharField(db_column='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='stations',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='state_code',
            field=models.CharField(blank=True, db_column='state_code', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stations',
            table='stations',
        ),
    ]
