# Generated by Django 5.2.7 on 2025-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_stations_address_alter_stations_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='type',
            field=models.CharField(blank=True, choices=[('POLICE', 'Police Station'), ('MILITARY', 'Military'), ('HOSPITAL', 'Hospital'), ('FIRE', 'Fire Station')], max_length=10, null=True),
        ),
    ]
