# Generated by Django 5.2.7 on 2025-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_stations_status_alter_stations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
