# Generated by Django 5.2.7 on 2025-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_stations_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='timestamp',
            field=models.CharField(db_column='timestamp', max_length=255),
        ),
    ]
