# Generated by Django 5.2.7 on 2025-12-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_location_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='incident_types',
            field=models.CharField(blank=True, choices=[('ROBBERY', 'Robbery'), ('ACCIDENT', 'Accident'), ('RIOT', 'Riot'), ('KIDNAPPING', 'Kidnapping'), ('TERRORISM', 'Terrorism'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='High_Risk_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('risk_types', models.CharField(choices=[('ROBBERY', 'Robbery'), ('ACCIDENT', 'Accident'), ('RIOT', 'Riot'), ('KIDNAPPING', 'Kidnapping'), ('TERRORISM', 'Terrorism'), ('OTHER', 'Other')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
