# Generated by Django 5.2.7 on 2025-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_location_incident_types_high_risk_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_risk_area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
