# Generated by Django 5.2.7 on 2025-12-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_location_detail_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='risk_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
