# Generated by Django 5.2.7 on 2025-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_feed_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
